export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
import './styles/globals.scss';
// import "./styles/layout.scss"
import './styles/variables.scss';

import { Karla, Inconsolata } from 'next/font/google';
import { UserProvider } from '@auth0/nextjs-auth0/client';

export const karla = Karla({
  subsets: ['latin'],
  variable: '--font-karla',
  weights: ['400', '700'],
});

export const inconsolata = Inconsolata({
  subsets: ['latin'],
  variable: '--font-inconsolata',
  weights: ['200', '300', '400', '500', '600', '700', '800', '900'],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${karla.variable} ${inconsolata.variable}`}>
      <UserProvider>
      <body>{children}</body>
     </UserProvider>
    </html>
  );
}
